sysdiglabs/terraform-google-secure-for-cloud

.pre-commit-config.yaml
`no-commit-to-branch` fails to execute in the CI of the master branch, this commit removes the pre-commit hook
=> fix(ci): Remove no-commit-to-branch pre-commit for CI in master

modules/cloud-connector/README.md, modules/cloud-connector/main.tf
The new HTTP + PubSub + AuditLog ingestor allows us to retrieve the messages with an Eventarc trigger and sleep the service if no messages are delivered, waking it up again when there are new messages.
=> feat: Add AuditSink + PubSub event delivery

README.md, main.tf, modules/cloud-connector/README.md, modules/cloud-connector/main.tf, modules/cloud-connector/variables.tf, variables.tf
This PR modifies:
- Adds the `naming_prefix` variable that was removed in previous versions.
- Increases the logging retrieved from PubSub to retrieve also the data_access logs.
- Add `max_instances` variable to be able to scale horizontally on large accounts.
- Locks the access to internal resources, so the endpoint is only accessible from PubSub.
=> feat: Add naming_prefix, increase logging, remove max instances

modules/cloud-connector/README.md, modules/cloud-connector/main.tf
Removes unneeded `roles/logging.viewer` permission, since the logs will be received through HTTP requests via PubSub
=> chore: Remove unneeded permission

README.md, main.tf, modules/cloud-scanning/README.md, modules/cloud-scanning/main.tf, modules/cloud-scanning/variables.tf, modules/cloud-scanning/versions.tf, variables.tf
Adds the new cloud-scanning module with PubSub based notifications to the cloud-scanning component. 
The `create_gcr_topic` variable is set to `false` by default to keep the backwards compatibility with existing Terraform deployments.
The `gcr` PubSub topic must exist for cloud-scanning to scan images pushed to GCR. If it doesn't exist, it can be deployed by setting `create_gcr_topic` to `true`.
=> feat: Add cloud-scanning module

modules/cloud-scanning/README.md, modules/cloud-scanning/main.tf
Adds a required environment variable for cloud-scanning to execute Cloud Build events with a service account, and also creates an IAM privilege for this ServiceAccount to self-impersonate itself in Cloud Build.
=> fix: Add required service account and IAM for cloud build

modules/cloud-connector/README.md, modules/cloud-connector/main.tf, modules/cloud-scanning/README.md, modules/cloud-scanning/main.tf
Enables all required project services while installing so new accounts don't face errors on the installation. It keeps them enabled if the components are removed, but no pricing should be charged if they are not being used.
=> feat: Enable all required project services on install

modules/cloud-scanning/README.md, modules/cloud-scanning/main.tf
There was a missing secret access to be given to the service account that executes the inline image scan.
=> fix: Add secret access to service account

modules/cloud-connector/README.md, modules/cloud-connector/main.tf, modules/cloud-scanning/README.md, modules/cloud-scanning/main.tf
Removes the `google_project_service` resources because of some inconsistency errors while deploying the module. Sometimes it takes a while for the APIs to become ready, and fails to create the resources. The API will be documented as required before applying the module.
=> chore: Remove all google_project_service resources

examples/organization/README.md, examples/organization/main.tf, examples/organization/variables.tf, examples/single-project/main.tf, modules/infrastructure/organization_sink/README.md, modules/infrastructure/organization_sink/main.tf, modules/infrastructure/organization_sink/variables.tf, modules/infrastructure/project_sink/README.md, modules/infrastructure/project_sink/main.tf, modules/infrastructure/project_sink/variables.tf
Adds example for organizational cloud-scanning
=> feat: Add organizational support for cloud-scanning

modules/services/cloud-bench/main.tf
If the benchmark task is created before the other resources, and the other resources fail, the benchmark task will start running, but generate a lot of errors as onboarding has not been completed. 
This PR ensures that all the required resources are created before the benchmark task.
=> fix: Create benchmark task last

README.md, examples/organization/README.md, examples/organization/main.tf, examples/organization/variables.tf, examples/single-project/variables.tf, modules/infrastructure/organization_sink/variables.tf, modules/infrastructure/project_sink/variables.tf, modules/infrastructure/secrets/variables.tf, modules/services/cloud-bench/README.md, modules/services/cloud-bench/main.tf, modules/services/cloud-bench/variables.tf, modules/services/cloud-connector/variables.tf, modules/services/cloud-scanning/variables.tf
=> example:organizational consolidation

modules/services/cloud-bench/trust_relationship/main.tf, modules/services/cloud-connector/README.md, modules/services/cloud-connector/versions.tf, modules/services/cloud-scanning/README.md, modules/services/cloud-scanning/versions.tf
The service account running GCP benchmarks requires `bigquery.tables.list`
=> Update Service Account Roles

.kitchen.yml, README.md
=> docs: remove CIEM capability from gcp

modules/services/cloud-bench/trust_relationship/main.tf
Cloud bench was creating cloud accounts in the backend storing the project name instead of the project id. In most cases this is fine, however if the project name contains capital letters, the project id defaults to the lowercased version of the name.
For customers with capital letters in their project names, this was leading to errors like: 
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting 
https://bigquery.googleapis.com/bigquery/v2/projects/ConfidentialNode/datasets?alt=json returned "Invalid project ID 
'ConfidentialNode'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include 
domain name separated by a colon. IDs must start with a letter and may not end with a dash.">```
=> fix(bench) Use projectID instead of project name

examples/single-project-k8s/README.md, examples/single-project-k8s/benchmark.tf, examples/single-project-k8s/versions.tf
The single-project-k8s example is missing the `sysdig` and `google-beta` providers, causing the module to fail.
=> fix(single-project-k8s) Add missing providers to k8s example

.github/workflows/issues-slack-notify.yml, modules/services/cloud-connector/README.md
Add an action to notify slack when an issue is opened
=> chore: add issue opened slack notification action

examples/organization/.generate-providers.sh, examples/organization/README.md, examples/single-project-k8s/README.md, examples/single-project/README.md, examples/trigger-events/README.md, modules/infrastructure/organization_sink/README.md, modules/infrastructure/project_sink/README.md, modules/infrastructure/pubsub_subscription/README.md, modules/infrastructure/secrets/README.md, modules/services/cloud-connector/README.md, use-cases/org-k8s-threat-compliance.md
Few minor improvements. Removed the validation step since that endpoint doesn't support GCP yet
=> Doc usecase k8 only update

examples/organization/README.md, examples/single-project-k8s/README.md, examples/single-project/README.md, examples/trigger-events/README.md, modules/infrastructure/organization_sink/README.md, modules/infrastructure/project_sink/README.md, modules/infrastructure/pubsub_subscription/README.md, modules/infrastructure/secrets/README.md, modules/infrastructure/secrets/data.tf, modules/infrastructure/secrets/main.tf, modules/services/cloud-connector/README.md
Update the module to create secret in location specified in google provider configuration instead of global.
=> feat: pin down secure-api-secret location from global to specific

modules/services/cloud-connector/README.md, modules/services/cloud-connector/variables.tf
Update cloud connector image using sysdig public registry: `us-docker.pkg.dev/sysdig-public-registry/secure-for-cloud/cloud-connector`
=> build: update cloud connector image hosted at sysdig registry

.github/workflows/pre-commit.yaml, .pre-commit-config.yaml, Makefile, README.md, examples/single-project-k8s/credentials.tf, modules/infrastructure/cloud_build_permission/main.tf, modules/services/cloud-connector/pubsub_permissions.tf
Why: Image scanning is run from inside a container. As it needs to get the image from the registry it needs a token to get it from the registry.
How to avoid security issues: As in the next implementation scanning will be run from within cloudrun which has needed permissions and won't need a token.
Warning: Organization users musn't be able to impersonate as the created service account.
=> fix: terrascan compliance

Makefile, examples/organization/README.md, examples/organization/benchmark.tf, examples/organization/main.tf, examples/organization/variables.tf, examples/single-project-k8s/README.md, examples/single-project-k8s/variables.tf, examples/single-project/README.md, examples/single-project/variables.tf, modules/services/cloud-bench/README.md, modules/services/cloud-bench/variables.tf
during a customer escalation we saw that both role and service account conflict due to GCP softdelete  + previously existing resource
for single account it was already done, but organizational example lacked the `var.name` prefix insertion on both items.
this PR adds both from the example layer.
**side-quest**
- added a readme for benchmark since it was empty
- clarified bit more `var.name` usage on all examples
=> refactor: avoid benchmark role collision with var.name

examples/single-project/README.md, examples/single-project/main.tf, examples/single-project/variables.tf
=> chore: Add configurable cloud connector image in example single project

README.md, examples/organization-org_compliance/main.tf, modules/services/cloud-bench-workload-identity/main.tf, modules/services/cloud-bench-workload-identity/variables.tf
Certain variables used in the example main.tf were only used in one place in a single submodule. This PR moves those variables/locals closer to where they are used, to simplify the variables needed when using the module. 
This also allows the module to be used as a standalone building block.
Manually verified by onboarding a GCP org and running a benchmark
=> refactor(bench): Refactor Org WIF module to simplify variables

examples/organization-org_compliance/main.tf, examples/organization/main.tf, examples/single-project/main.tf, modules/services/cloud-connector/README.md, modules/services/cloud-connector/main.tf, modules/services/cloud-connector/variables.tf
Modifies the deployment of the cloud-connector to accept the secret ID of the Secure API Token so it can be used instead of plain-text env var.
=> feat: provide secure api token via secret manager in cloud run

use-cases/no-terraform-org-k8s-threat-compliance.md
Benchmarks tasks are no longer supported or required, and compliance scans are triggered automatically on creation of an account
=> Remove legacy benchmark task creation

modules/services/cloud-bench-workload-identity/main.tf
- support project id from subfolders in gcp org
=> support project id from subfolders in gcp org

.github/workflows/pre-commit.yaml, examples/organization-org_compliance/README.md, examples/organization-org_compliance/versions.tf, examples/organization/README.md, examples/organization/versions.tf, examples/single-project-k8s/README.md, examples/single-project-k8s/versions.tf, examples/single-project/README.md, examples/single-project/versions.tf, modules/services/cloud-bench-workload-identity/versions.tf, modules/services/cloud-bench/README.md, modules/services/cloud-bench/versions.tf, modules/services/cloud-connector/README.md, modules/services/cloud-connector/main.tf, modules/services/cloud-connector/versions.tf
Removes the max terraform version so newer versions can still use this module.
=> chore: remove max terraform version limit
